HomeWork 14
verovkin/robot_dreams pull request #11
Opened 2023-01-20 19:18 UTC by verovkin

working on third one… the toughest one…

2023-01-22 18:24 UTC, verovkin commented on 14/phonebook.py
> +    regex = "(\+?38)?0\d{9}$"
validation function

2023-01-26 22:56 UTC, klymenok requested changes

2023-01-26 22:56 UTC, klymenok commented on 14/email_change2.py
> +email_regex = re.compile(r'(?<=.).(?=[^@]*?@)|(?:(?<=@)|(?!^)(?=[^@]*$))(.)(?=.*\.)|(?:(?<=\.)(?=[^.]+$)|(?!^)(?=[^@.]*$))[^.](?!$)', re.MULTILINE)
Even don't know how to debut this, but in your case, the replacement keeps only the last letter of an email. And it should keep both first and last.

2023-01-27 13:09 UTC, verovkin commented
Edits done.
made a bit easier that RegEx

2023-01-29 15:36 UTC, klymenok approved these changes
Looks good!

2023-01-29 16:56 UTC, merged