HW-30 done
verovkin/robot_dreams pull request #18
Opened 2023-03-20 22:16 UTC by verovkin

done :)

2023-03-25 18:29 UTC, klymenok requested changes

2023-03-25 18:29 UTC, klymenok commented on 30/task2.py
> +    latitude = city_res_data.get("results")[0]["latitude"]
You would get an error here if user entered a non-existing city

2023-03-25 19:15 UTC, verovkin commented
Rewrote code in OOP, interesting is it written in such way :)

2023-03-28 21:49 UTC, klymenok requested changes

2023-03-28 21:49 UTC, klymenok commented on 30/task2.py
> +city = City()
Good try, but to improve your OOP approach, I would suggest the following:
1. Use objects and methods and something that you can use and reuse
2. Initialize object's properties in constructor and raise error if something is wrong. You can take `name` as a parameter in the constructor and then call `protected` method `set_coordinates`, to init attributes `self.lat` and `self.lon`
3. Make methods smaller and responsible only for some atomic task

In the end you should get something like this:
```
class City:
    def __init__(self, name):
        self.name = name
        self._set_coordinates()

    def _set_coordinates(self):
        # some code here
        if not lat or not lon:
            raise ValueError('No such city')
        self.lat = lat
        self.lon = lon

    def print_weather(self):
        # some code here
        if weather.status_code == 200:
            print(...)
        else:
            print(...)

city_name = input()
try:
    city = City(city_name)
except ValueError as e:
    print(e)
else:
    city.print_weather()
```

If you want to go further, you can create a separate class to work with weather API and unload your city class. You can keep in city only city-related information:
```
class City:
    def __init__(self, name):
        self.name = name
        self._set_coordinates()

    def _set_coordinates(self):
        self.lat, self.lon = WeatherService.get_coordinates(self.name)

    def print_weather(self):
        weather_data = WeatherService.get_current_weather(self.lat, self.lon)
        if weather_data:
            print(...)
        else:
            print(...)

2023-03-29 13:17 UTC, verovkin commented on 30/task2.py
> +city = City()
why not include city name enter in City class __init__?

that way we can hide this in the class:
`try:
    city = City(city_name)
except ValueError as e:
    print(e)
else:
    city.print_weather()`

2023-03-29 13:32 UTC, verovkin commented on 30/task2.py
> +city = City()
for user it will be easier to use library without try-except

2023-03-29 13:33 UTC, verovkin commented on 30/task2.py
> +city = City()
incapsulation, что ли )

2023-03-29 13:42 UTC, verovkin commented on 30/task2.py
> +city = City()
I meen we can handle exceptions inside City class. if no city - ask user to enter again

2023-03-30 21:13 UTC, klymenok commented on 30/task2.py
> +city = City()
It depends on what your `City` will do. Your suggestion also makes sense. You can check city existing with `WeatherService` on init

2023-03-30 21:14 UTC, klymenok requested changes

2023-03-30 21:14 UTC, klymenok commented on 30/task2.py
> +            "latitude": lon,
Lat and Lon are switched here and the result is not for the city entered by a user

2023-03-31 07:31 UTC, verovkin commented
In this code I use class methods of WeatherService, so, as I understood - no instance is created and no __init__ method is called?

2023-03-31 19:23 UTC, klymenok commented
> In this code I use class methods of WeatherService, so, as I understood - no instance is created and no **init** method is called?

Correct. And, you can also implement those methods as `static` since you don't need a reference to your class.

Regular methods - first argument `self` keeps an instance of a class
Class methods - first argument `cls` keeps a class itself
Static methods - arguments are simple arguments, a method has no access either to class or object

2023-03-31 19:23 UTC, klymenok approved these changes
Looks good!

2023-03-31 19:34 UTC, merged