no forms yet
verovkin/robot_dreams pull request #26
Opened 2023-04-30 10:04 UTC by verovkin

2023-05-01 10:48 UTC, klymenok requested changes
Дійсно, форм трошки не вистачає 🙂

2023-05-01 10:48 UTC, klymenok commented on django/purchase/migrations/0001_initial.py
А що з міграціями сталося? Здається, їх не треба було видаляти

2023-05-01 10:48 UTC, klymenok commented on django/purchase/views.py
> +    fields = ('',)
Пустий tuple fields є причиною помилки

2023-05-01 10:51 UTC, verovkin commented on django/purchase/migrations/0001_initial.py
після маніпуляцій з гітом, воно почало помилки видавати, видаливши міграції запрацювало )
в мене локально працює )

2023-05-01 10:56 UTC, verovkin commented on django/purchase/migrations/0001_initial.py
і там же є інішіал мігрейшон ), як з нуля?

2023-05-01 11:25 UTC, verovkin commented on django/purchase/views.py
> +    fields = ('',)
created user form as in video, but getting error…
`NoReverseMatch at /users/create
Reverse for 'user-detail' not found. 'user-detail' is not a valid view function or pattern name.`
but it's exactly as in lessen, why?

2023-05-01 11:30 UTC, verovkin commented on django/purchase/views.py
> +    fields = ('',)
Для коректної роботи форми, view має містити атрибут success_url... я шось такого не знайшов на гіті

2023-05-01 12:46 UTC, verovkin commented
done :)

2023-05-03 11:27 UTC, klymenok approved these changes
Goods look!

2023-05-03 14:25 UTC, merged