Docker2
verovkin/robot_dreams pull request #31
Opened 2023-05-17 18:09 UTC by verovkin

2023-05-23 19:44 UTC, klymenok requested changes

2023-05-23 19:44 UTC, klymenok commented on flask-homework/docker-compose.yml
> +  celery_worker:
У flask celery не потрібно використовувати

2023-05-23 19:44 UTC, klymenok commented on flask-homework/docker-compose.yml
> +  celery_beat:
У flask celery не потрібно використовувати

2023-05-23 19:44 UTC, klymenok commented on flask-homework/docker-compose.yml
> +    command: guinicorn --bing :8000 --workers 3 -t 60 flask.wsgi:application
image не містить gunicorn

2023-05-23 19:44 UTC, klymenok commented on flask-homework/docker-compose.yml
> +    command: guinicorn --bing :8000 --workers 3 -t 60 flask.wsgi:application
Також проект flask не містить `wsgi.py`

2023-05-26 18:41 UTC, verovkin commented
how about now? :)

2023-05-28 17:15 UTC, klymenok approved these changes
LGTM!

2023-05-28 17:19 UTC, merged